graph LR
    CLI["CLI"]
    Dev1["Device 1"]
    Dev2["Device 2"]
    Tools(["Tools"])

    subgraph ServerProcess["Server Process"]
        subgraph ChanMgr["Channel Manager"]
            CDP["Channel Device<br/>Plugin"]
        end

        subgraph CommMgr["Communication Manager"]
            IQ[("Inbound<br/>Queue")]
            OQ[("Outbound<br/>Queue")]
        end

        subgraph AgentMgr["Agent Manager"]
            PM["Process<br/>Message"]
        end

        HTTP["HTTP Server"]

        CDP --> IQ
        IQ --> PM
        PM --> OQ
        OQ --> CDP
        PM -->|invoke| Tools
        HTTP -->|invoke| Tools
    end

    CLI -->|use| Tools
    Dev1 <-->|WebSocket| CDP
    Dev2 <-->|WebSocket| CDP
